config/routes.rb
Rails.application.routes.draw do

  get 'browse' => 'browse#index'

  get 'folders' => 'browse#folders'
  get 'songs' => 'browse#songs'
  get 'search' => 'browse#search'

  get 'welcome/index'

  root 'welcome#index'

end

app/models/folder.rb
class Folder < ActiveRecord::Base
  scoped_search on: [:path]
  has_many :folder_songs
  has_many :songs, through: :folder_songs

  def key
    id
  end
end

app/models/folder_song.rb
class FolderSong < ActiveRecord::Base
  belongs_to :song
  belongs_to :folder, counter_cache: :songs_count
end

app/models/song.rb
class Song < ActiveRecord::Base
  scoped_search on: [:artist, :album, :title]
  has_many :folder_songs
  has_many :folders, through: :folder_songs

  def key
    id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/browse_controller.rb
class BrowseController < ApplicationController
  def index
    @folder = Folder.where(full_path: params[:path]).first
    @folder ||= Folder.order('songs_count desc, depth desc').limit(1).first
    #logger.info @folder.inspect
    depth = @folder.try(:depth) || 0
    path = @folder.try(:full_path) || ''

    @path_parts = []
    pparts = path.split(/\//)
    pparts.shift
    path_agg = ""
    pparts.each_with_index do |ppath, i|
      path_agg +=  "/" + ppath
      @path_parts << [ppath,path_agg]
    end

    @folders = Folder.order('depth asc, path asc')\
              .where('full_path like ?', "#{path}%")\
              .where(depth: depth+1)\
              .page(params[:folder_page] || 0).per(100)

    @songs = @folder.songs.page(params[:song_page]) if @folder.present?
  end

  def folders
    folder = Folder.where(full_path: params[:path]).first
    folder ||= Folder.order('songs_count desc, depth desc').limit(1).first
    #
    depth = folder.try(:depth) || 0
    path = folder.try(:full_path) || ''
    folders = Folder.order('depth asc, path asc')\
              .where('full_path like ?', "#{path}%")\
              .where(depth: depth+1)
              #.page(params[:folder_page] || 0).per(100)
    songs = folder.songs.page(params[:song_page]) if folder.present?

    render json: {
      folders: folders.as_json(methods: 'key'),
      songs: songs.as_json(methods: 'key')
    }
  end

  def songs
    folder = Folder.where(full_path: params[:path]).first
    folder ||= Folder.order('songs_count desc, depth desc').limit(1).first
    songs = folder.songs.page(params[:song_page]) if folder.present?
    render json: songs
  end

  def search
    term = params[:term]
    folders = Folder.search_for(term).page(1)
    songs = Song.search_for(term).page(1)
    render json: {
      folders: folders.as_json(methods: 'key'),
      songs: songs.as_json(methods: 'key')
    }
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout false
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/browse_helper.rb
module BrowseHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/browse/index.html.haml
.container-fluid
  .row
    .col-sm-12

      %ol.breadcrumb
        - @path_parts.each do |ppath, path_agg|
          %li= link_to ppath, "?path="+path_agg

  .row
    .col-sm-4
      .panel.panel-default
        .panel-heading
          .pull-right
            %a.btn.btn-default.btn-xs{href:'#folder_filters',data:{toggle:'collapse'}}
              = icon('filter')
          %a{href:'#folders',data:{toggle:'collapse'}} folders

        #folders.collapse.in
          .panel-body
            #folder_filters.collapse
              %form
                %input.form-control{name:'filter',type:'text',placeholder:'filter',value:params[:filter]}

            %table
              %tr
                %td
                  - last_path = @path_parts[-2].try(:second)
                  - if last_path.present?
                    = link_to icon('arrow-left'), "?path="+last_path, class: 'btn btn-default'
                %td
                  &nbsp;
                  = page_entries_info @folders

          /.btn-group
          /  - ('A'..'z').each do |l|
          /    %a.btn.btn-default{href:'#'}= l
          = paginate @folders, param_name: :folder_page

          %div#search.list-group
            - @folders.each do |folder|
              %a.folder.list-group-item{href: "?path=#{folder.full_path}"}
                .pull-right
                  .badge
                    = folder.songs_count
                %b= folder.path

          = paginate @folders, param_name: :folder_page
          
    .col-sm-4
      .panel.panel-default
        .panel-heading
          .pull-right
            %label
              %input{type:'checkbox'}
              Recursive
            %a.btn.btn-default.btn-xs{href:'#song_filters',data:{toggle:'collapse'}}
              = icon('filter')
          %a{href:'#songs',data:{toggle:'collapse'}} songs
        #songs.collapse.in
          #song_filters.panel-body.collapse
            %input.form-control{name:'filter',type:'text',placeholder:'filter',value:params[:filter]}
          %div#songs.list-group
            - if @songs.present?
              %a.request-all.list-group-item.list-group-item-warning{data:{path: @folder.full_path}}
                %b request all
              - @songs.each do |song|
                %a.song.list-group-item{data:{hash: song.audio_hash, path: song.path}}
                  .pull-right
                    = song.artist
                  %b= song.title

    .col-sm-4
      %b requests
      %div#requests.list-group

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title RFK
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=edge")
    %meta(name="viewport" content="width=device-width, initial-scale=1")
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
    = javascript_include_tag 'application', 'data-turbolinks-track' => true 
    = csrf_meta_tags 
  %body
    %ul.nav.nav-pills
      %li
        = link_to "rfk", :root
      %li
        = link_to "browse", browse_path
    =yield

app/views/welcome/_angular_now_playing.html.haml
.panel.panel-default(ng-app='welcomeApp' ng-controller='welcomeCtrl')
  .panel-body

    .row
      /.col-xs-1
      /  %button.btn.btn-default.btn-xs
      /    = fa_icon('tag',class: 'text-muted')
      /.col-xs-11
      .col-xs-12
        .pull-right
          .btn-group.hidden-xs
            %button.btn.btn-default(ng-click='playpause()')
              = icon('play')
              = icon('pause')

          .btn-group.hidden-xs
            %button.btn.btn-success(ng-click='reward()')
              = icon('thumbs-up')
            %button.btn.btn-danger(ng-click='skip()')
              = icon('thumbs-down')

        .btn-group.visible-xs
          %button.btn.btn-xlarge.btn-default(ng-click='playpause()')
            = icon('play')
            = icon('pause')

        .btn-group.visible-xs
          %button.btn.btn-xlarge.btn-success(ng-click='reward()')
            = icon('thumbs-up')
          %button.btn.btn-xlarge.btn-danger(ng-click='skip()')
            = icon('thumbs-down')
        %hr.clear.visible-xs
        %b {{ currentSong.Title }}
        %br
        {{ currentSong.Artist }}
        %br
        .pull-right
          %span.label.label-default.bg-supermuted {{currentSong.Rank}}
        %i {{ currentSong.Album }}
  .panel-footer.text-muted
    %i Previous song
    %br
    %button.btn.btn-default.btn-xs
      = icon('tag',class: 'text-muted')
    .pull-right
      %span.label.label-default.bg-supermuted {{lastSong.Rank}}
    %b {{ lastSong.Title }}
    \/ 
    {{ lastSong.Artist }}
    \/
    %i {{ lastSong.Album }}

app/views/welcome/_angular_requests.html.haml
%ul.list-group
  %li.list-group-item
    .pull-right
      %button.btn.btn-default.btn-xs(ng-click="clearRequests()")
        Clear
    %b Requests
    .label.label-default
      {{ requests.length }}
  %li.list-group-item(ng-repeat="song in requests")
    .pull-right
      .label.label-default.bg-supermuted {{song.Rank}}
    %small.text-muted.hash {{song.Hash}}
    %span.path {{song.Path}}

app/views/welcome/_angular_search.html.haml
%form.form-inline
  .input-group
    %span.input-group-addon
      = icon('search')
    %input.form-control(ng-model='term' type='text' ng-change="search()")
    %span.input-group-btn
      %button.btn.btn-default(ng-click="searchRequest()")
        = icon('play')
        = icon('list')

%ul.list-group
  %li.list-group-item(ng-repeat="song in search_songs")
    %small.text-muted.hash {{song.Hash}}
    %span.path {{song.Path}}

app/views/welcome/index.html.haml
!!!
%html
  %head
    %title rfk
    %meta(name="viewport" content="width=device-width, initial-scale=1")
    = stylesheet_link_tag    'application', media: 'all', debug: false
  %body
    .container-fluid
      -#= react_component('Player', nil, {id: 'player'})
      #player

= javascript_include_tag 'application', debug: true